const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Persist,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{planoDeStart: 0},
	{START: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Mouse: 0},
	{Sólido: 0},
	{bloco: 0},
	{muro: 0},
	{correntes: 0},
	{madeira: 0},
	{Sprite8: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Sprite: 0},
	{MinerPersonagem: 0},
	{Teclado: 0},
	{fogo: 0},
	{fogo2: 0},
	{correntesprata: 0},
	{Senóide: 0},
	{Sprite2: 0},
	{moedas: 0},
	{Sprite3: 0},
	{portal: 0},
	{Sprite5: 0},
	{VIDA: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Projétil: 0},
	{DarAVolta: 0},
	{Persistir: 0},
	{Sprite4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{start2: 0},
	{exit: 0},
	{Sprite6: 0},
	{portal2: 0},
	{playGameOver: 0},
	{exitgameover: 0},
	{Vidas: 0}
];

self.InstanceType = {
	planoDeStart: class extends self.ITiledBackgroundInstance {},
	START: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	bloco: class extends self.ISpriteInstance {},
	muro: class extends self.ISpriteInstance {},
	correntes: class extends self.ISpriteInstance {},
	madeira: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MinerPersonagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	fogo: class extends self.ISpriteInstance {},
	fogo2: class extends self.ISpriteInstance {},
	correntesprata: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	moedas: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	VIDA: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	start2: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	playGameOver: class extends self.ISpriteInstance {},
	exitgameover: class extends self.ISpriteInstance {}
}